// examples/basic-svelte/src/App.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';

  type Todo = {
    id: number;
    text: string;
    completed: boolean;
  };

  let todos: Todo[] = [
    { id: 1, text: "Learn Nuclo", completed: false },
    { id: 2, text: "Build a Todo App", completed: false },
    { id: 3, text: "Deploy to Production", completed: false },
  ];
  let nextId = 4;
  let inputValue = "";
  let visible = false;
  let counter = 0;
  let isPlaying = false;
  let intervalId: number | undefined;

  $: if (isPlaying) {
    if (intervalId === undefined) {
      intervalId = setInterval(() => {
        counter += 1;
      }, 1000);
    }
  } else {
    if (intervalId !== undefined) {
      clearInterval(intervalId);
      intervalId = undefined;
    }
  }

  onDestroy(() => {
    if (intervalId !== undefined) {
      clearInterval(intervalId);
    }
  });

  function addTodo() {
    if (!inputValue.trim()) return;
    todos = [...todos, { id: nextId, text: inputValue.trim(), completed: false }];
    nextId += 1;
    inputValue = "";
  }

  function toggleTodo(id: number) {
    todos = todos.map((todo) =>
      todo.id === id ? { ...todo, completed: !todo.completed } : todo
    );
  }

  function deleteTodo(id: number) {
    todos = todos.filter((todo) => todo.id !== id);
  }

  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter') {
      addTodo();
    }
  }
</script>

<div class="body">
  <div class="container">
    <h1 class="header">📝 Todo List</h1>

    <div class="input-container">
      <input
        class="input"
        type="text"
        placeholder="What needs to be done?"
        bind:value={inputValue}
        on:keydown={handleKeyDown}
      />
      <button class="add-button" on:click={addTodo}>Add</button>
    </div>

    <div>
      <input
        type="checkbox"
        id="visibilityToggle"
        bind:checked={visible}
      />
      <span>is this visible: </span>
      {visible ? "yes" : "no"}
    </div>

    <div class="input-container">
      <button
        class="add-button"
        on:click={() => isPlaying = true}
      >
        Play
      </button>
      <button
        class="delete-button"
        on:click={() => isPlaying = false}
      >
        Stop
      </button>
    </div>

    <div>
      <button on:click={() => counter += 1}>Increment Counter</button>
      <div>Counter: {counter}</div>
    </div>

    {#if todos.length === 0}
      <div>No todos yet! Add one above.</div>
    {:else}
      <div class="todo-list">
        {#each todos as todo (todo.id)}
          <div class="todo-item">
            <span class="drag-handle">⇅</span>
            <input
              class="checkbox"
              type="checkbox"
              checked={todo.completed}
              on:change={() => toggleTodo(todo.id)}
            />
            <span class={todo.completed ? "todo-text-completed" : "todo-text"}>
              {todo.text}
            </span>
            <button class="delete-button" on:click={() => deleteTodo(todo.id)}>
              Delete
            </button>
          </div>
        {/each}
      </div>
    {/if}
  </div>
</div>

// examples/basic-react/src/App.tsx
import { useState, useEffect } from 'react'
import './App.css'

type Todo = {
  id: number;
  text: string;
  completed: boolean;
};

function App() {
  const [todos, setTodos] = useState<Todo[]>([
    { id: 1, text: "Learn Nuclo", completed: false },
    { id: 2, text: "Build a Todo App", completed: false },
    { id: 3, text: "Deploy to Production", completed: false },
  ]);
  const [nextId, setNextId] = useState(4);
  const [inputValue, setInputValue] = useState("");
  const [visible, setVisible] = useState(false);
  const [counter, setCounter] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);

  useEffect(() => {
    let intervalId: number | undefined;
    if (isPlaying) {
      intervalId = setInterval(() => {
        setCounter((prev) => prev + 1);
      }, 1000);
    }
    return () => {
      if (intervalId !== undefined) {
        clearInterval(intervalId);
      }
    };
  }, [isPlaying]);

  const addTodo = () => {
    if (!inputValue.trim()) return;
    setTodos([...todos, { id: nextId, text: inputValue.trim(), completed: false }]);
    setNextId(nextId + 1);
    setInputValue("");
  };

  const toggleTodo = (id: number) => {
    setTodos(todos.map((todo) =>
      todo.id === id ? { ...todo, completed: !todo.completed } : todo
    ));
  };

  const deleteTodo = (id: number) => {
    setTodos(todos.filter((todo) => todo.id !== id));
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      addTodo();
    }
  };

  return (
    <div className="body">
      <div className="container">
        <h1 className="header">📝 Todo List</h1>

        <div className="input-container">
          <input
            className="input"
            type="text"
            placeholder="What needs to be done?"
            value={inputValue}
            onInput={(e) => setInputValue((e.target as HTMLInputElement).value)}
            onKeyDown={handleKeyDown}
          />
          <button className="add-button" onClick={addTodo}>Add</button>
        </div>

        <div>
          <input
            type="checkbox"
            id="visibilityToggle"
            checked={visible}
            onChange={(e) => setVisible(e.target.checked)}
          />
          <span>is this visible: </span>
          {visible ? "yes" : "no"}
        </div>

        <div className="input-container">
          <button
            className="add-button"
            onClick={() => setIsPlaying(true)}
          >
            Play
          </button>
          <button
            className="delete-button"
            onClick={() => setIsPlaying(false)}
          >
            Stop
          </button>
        </div>

        <div>
          <button onClick={() => setCounter(counter + 1)}>Increment Counter</button>
          <div>Counter: {counter}</div>
        </div>

        {todos.length === 0 ? (
          <div>No todos yet! Add one above.</div>
        ) : (
          <div className="todo-list">
            {todos.map((todo) => (
              <div key={todo.id} className="todo-item">
                <span className="drag-handle">⇅</span>
                <input
                  className="checkbox"
                  type="checkbox"
                  checked={todo.completed}
                  onChange={() => toggleTodo(todo.id)}
                />
                <span className={todo.completed ? "todo-text-completed" : "todo-text"}>
                  {todo.text}
                </span>
                <button className="delete-button" onClick={() => deleteTodo(todo.id)}>
                  Delete
                </button>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}

export default App
